# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxTableCell' do
    pod 'RxCocoa'
    pod 'RxSwift'
    pod 'DTTableViewManager'#, '~> 6.0.0-beta.3'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxTableCell

end
